//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestAnalyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestAnalyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first line within the test body must be the comment &apos;// Arrange.&apos; .
        /// </summary>
        internal static string ArrangeCommentMustBeFirstLineDescription {
            get {
                return ResourceManager.GetString("ArrangeCommentMustBeFirstLineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body of the unit test &apos;{0}&apos; does not have its first line with the comment &apos;// Arrange.&apos;.
        /// </summary>
        internal static string ArrangeCommentMustBeFirstLineMessage {
            get {
                return ResourceManager.GetString("ArrangeCommentMustBeFirstLineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first line of the body of a unit test must be &apos;// Arrange.&apos;.
        /// </summary>
        internal static string ArrangeCommentMustBeFirstLineTitle {
            get {
                return ResourceManager.GetString("ArrangeCommentMustBeFirstLineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document the body of the test method with the AAA (Arrange.Act.Assert.) comments.
        /// </summary>
        internal static string UseAAACommentsAnalyzerDescription {
            get {
                return ResourceManager.GetString("UseAAACommentsAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body of the unit test method &apos;{0}&apos; must include the following comments // Arrange. // Act. // Assert. on this order.
        /// </summary>
        internal static string UseAAACommentsAnalyzerMessage {
            get {
                return ResourceManager.GetString("UseAAACommentsAnalyzerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the comments // Arrange. // Act. // Assert..
        /// </summary>
        internal static string UseAAACommentsAnalyzerTitle {
            get {
                return ResourceManager.GetString("UseAAACommentsAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit test class names should end with &apos;UnitTests&apos;.
        /// </summary>
        internal static string UseUnitTestsSuffixDescription {
            get {
                return ResourceManager.GetString("UseUnitTestsSuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit test class name &apos;{0}&apos; should end with &apos;UnitTests&apos;..
        /// </summary>
        internal static string UseUnitTestsSuffixMessage {
            get {
                return ResourceManager.GetString("UseUnitTestsSuffixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;UnitTests&apos; suffix.
        /// </summary>
        internal static string UseUnitTestsSuffixTitle {
            get {
                return ResourceManager.GetString("UseUnitTestsSuffixTitle", resourceCulture);
            }
        }
    }
}
